# Generated by Django 4.1.4 on 2022-12-27 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_cart_product_cart_products_alter_cart_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='id_order',
            new_name='in_order',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='order',
            new_name='orders',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 27, 7, 36, 46, 908803, tzinfo=datetime.timezone.utc), verbose_name='Дата получения заказа'),
        ),
    ]
